version: "3.8"

services:
  backend:
    build: ./backend
    container_name: node_backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb+srv://anany:anany123@cluster0.j0uhrrv.mongodb.net/employmentDB?retryWrites=true&w=majority&appName=Cluster0
    volumes:
      - ./backend:/app  # optional for live reload, but beware node_modules issues
    restart: always

  frontend:
    build:
      context: ./frontend/employement
    container_name: angular_frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    restart: always
    # volumes only if live reload chahiye, optional
    volumes:
      - ./frontend/employement:/app
      - /app/node_modules
